<?php

namespace CodeOfDigital\LaravelUrlShortener;

use Illuminate\Support\ServiceProvider;

class UrlShortenerServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->mergeConfigFrom(__DIR__.'/../config/url-shortener.php', 'url-shortener');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
